FROM ubuntu

RUN apt-get update
RUN apt-get install -y python
RUN apt-get install -y python-pip
RUN apt-get install -y supervisor

# Setup django
WORKDIR /django_example
ADD . /django_example
RUN pip install -r requirements.txt

# Setup supervisord
RUN mkdir -p /var/log/supervisor
COPY production/worker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY production/worker/celeryd.conf /etc/supervisor/conf.d/celeryd.conf

CMD ["/usr/bin/supervisord"]